CREATE TABLE IF NOT EXISTS `ppds_registry` 
(
	`ID` int NOT NULL AUTO_INCREMENT,	
	`REGISTRY_NUMBER` varchar(50) NULL,
	`DATE` datetime NOT NULL,
	`GETTING_TYPE` varchar(5) NOT NULL,
	`IKN` varchar(12) NOT NULL,
	`TRANSFER_CITY` varchar(255) NOT NULL,
	`TRANSFER_CITY_LINK` int(10) NOT NULL DEFAULT 0,
	`FILENAME` varchar(255) NOT NULL,	
	PRIMARY KEY (`ID`)
) AUTO_INCREMENT = 1;